name: Tests

on:
  workflow_dispatch:
    inputs:
      frontend_image:
        description: 'Frontend image'
        default: 'evercoinx/faraway:nft-collection-deployer-frontend'
        required: true
      backend_image:
        description: 'Backend image'
        default: 'evercoinx/faraway:nft-collection-deployer-backend'
        required: true
      retries:
        description: 'Retries - How many times to rerun a failed test'
        default: '2'
        required: false

jobs:
  e2e-tests:
    name: Smart Contract Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      RETRIES: ${{ inputs.retries }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

#      - name: Run frontend
#        uses: addnab/docker-run-action@v3
#        with:
#          image: ${{ inputs.frontend_image }}
#          args: -it -p 3000:3000
#
#      - name: Run backend
#        uses: addnab/docker-run-action@v3
#        with:
#          image: ${{ inputs.backend_image }}
#          args: -it -p 4000:4000

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm install
        shell: bash

      - name: Install linux deps
        run: |
          sudo apt-get install --no-install-recommends -y \
          fluxbox \
          xvfb

      - name: Tests
#        run: npm run test
        run: |
          Xvfb :0 -screen 0 1024x768x24 -listen tcp -ac &
          fluxbox &
          npx playwright test src/tests/test.spec.ts

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

